name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud config set run/region asia-southeast1
        gcloud config set run/platform managed
        gcloud builds submit \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/typee-frontend:${GITHUB_SHA} \
          --build-arg API_BASE_URL=${{ secrets.API_BASE_URL }} \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --substitutions=_REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }},\
          _REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }},\
          _REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }},\
          _REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }},\
          _REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }},\
          _REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy typee-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/typee-frontend \
          --allow-unauthenticated