name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        gcloud config set run/region asia-southeast1
        gcloud config set run/platform managed
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/typee-frontend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy typee-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/typee-frontend \
          --allow-unauthenticated